name: Tap List - Update Taps

on:
  workflow_dispatch:
jobs:
  the-rusty-bumblebee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Save current taps
        id: save-current-taps
        run: |
          pip install pyyaml
          cd ./tap-list/spots/the_rusty_bumblebee
          echo "taps="$(python parse.py)"" >> "$GITHUB_OUTPUT"
      - name: Refresh taps
        id: refresh-taps
        run: |
          pip install playwright
          playwright install-deps
          playwright install
          cd ./tap-list/spots/the_rusty_bumblebee
          python scrape.py > tap_list.yaml
          changes=$(git status --porcelain)
          if [ -z "$changes" ]; then
            echo "changes_detected=false" >> "$GITHUB_OUTPUT"
            echo "No changes to taps."
            exit 0
          fi
          echo "changes_detected=true" >> "$GITHUB_OUTPUT"
      - name: Update tap list
        if: ${{  steps.refresh-taps.outputs.changes_detected == 'true'  }}
        run: |
          cd ./tap-list/spots/the_rusty_bumblebee
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Tap List - rotating taps"
          git push
          python main.py rss -sha $(git rev-parse HEAD) -taps ${{  steps.save-current-taps.outputs.taps  }} | tee temp.xml > /dev/null
          git add .
          git commit -m "Tap List - updating RSS"
          git push