name: Update Taps

on:
  workflow_dispatch:
jobs:
  commit-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: The Rusty Bumblebee
        run: |
          pip install playwright
          playwright install-deps
          playwright install
          cd ./taplist/spots/the_rusty_bumblebee
          python scrape.py > taplist.yaml
      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Changes to `The Rusty Bumblebee` Taplist"
      - name: Push changes
        run: |
          if git diff --cached --quiet; then
            echo "No changes to push."
          else
            git push
          fi
